### ISSUE TITLE
Make x-axis linear on heterozygosity boxplots

### ISSUE THREAD

**Issue by redgcko7** [redgcko7/Coleonyx_elegans#4]
I plotted boxplots for heterozygosity of iPyrad de novo assemblies with different clustering thresholds to determine the optimal threshold value using this code in [ClustOpt_Plotting.R](https://github.com/redgcko7/Coleonyx_elegans/blob/main/iPyrad_tests/Bin/ClustOpt_Plotting.R) script:
```
#### boxplots for heterozygosity ####

# import data (text delimited file)
hetero <- read.delim("../Meta/Cele_hetero.csv", header = T)

#multiply values by 100 to get %
het_percent <- hetero*100

#change names of columns
new_names <- c("80", "85", "87", "90", "93", "94", "95", "96", "98")
names(het_percent) <- new_names

#reset plotting dimensions
par(mfrow=c(1,1))

#plot
png(filename = "../Figures/Cele_hetero.png", width = 300*10, height = 300*8, res = 300, units = "px")
boxplot(het_percent, notch = T, xlab = "Clustering threshold (% similarity)", ylab = "% heterozygous sites")
dev.off()
```

The [resulting graph](https://github.com/redgcko7/Coleonyx_elegans/blob/main/iPyrad_tests/Figures/Cele_hetero.png) has the different clustering thresholds along the x-axis (80, 85, 87, 90, 93, 94, 95, 96, 98). I would like these x-values to be plotted linearly so that the trend can be better visualized as the clustering threshold increases (i.e. the x-value distance from 80 to 85 should be spaced out, while the x-value distance from 94 to 95 closer together).

The input file 'Cele_hetero.csv' can be found [here](https://github.com/redgcko7/Coleonyx_elegans/blob/main/iPyrad_tests/Meta/Cele_hetero.csv).

**Comment by bc-anaisabel** [comment]
We need to first use `gather` to have the data the way ggplot needs it (from wide to long)

**Comment by AliciaMstt** [comment]
https://ggplot2.tidyverse.org/reference/scale_discrete.html para el scale

**Comment by redgcko7** [comment]
To plot in ggplot2, first we had to transform the data using the gather function in tidyr using this command:
```
transformed <- gather(data = het_percent, value = "80", "85", "87", "90", "93", "94", "95", "96", "98",key = "threshold", 1:9)
names(transformed)[2] <- "het" 
```

**Comment by arihelrnan** [comment]
In the Boxplot RDocumentation (https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/boxplot) you can find the `at` argument. With him you can give the locations where the boxplots should be drawn.  For example, you can use this argument: `boxplot(het_percent, notch = T, xlab = "Clustering threshold (% similarity)", ylab = "% heterozygous sites", at = c(c(80, 85, 87, 90, 93, 94, 95, 96, 98)))`

**Comment by bc-anaisabel** [comment]
What about changing tick marks?
http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels

```
# Set tick marks on y axis
# a tick mark is shown on every 5
p + scale_y_continuous(breaks=seq(0,40,5))
```

**Comment by redgcko7** [comment]
We tried with ggplot2, got close, but ultimately have not yet resolved the issue (with ggplot2).

Code we used:
```
# transform data with gather function in tidyr
transformed <- gather(data = het_percent, value = "80", "85", "87", "90", "93", "94", "95", "96", "98",key = "threshold", 1:9)
names(transformed)[2] <- "het" 

# plot
p <- ggplot(transformed, aes(x = threshold, y = het, fill = "het")) +
geom_boxplot() +
scale_x_discrete(breaks = c("80", "85", "90", "95", "100"), labels= c("80", "85", "90", "95", "100"))
p
```

We we able to change the x labels so that they are every 5, but we still need to figure out how to change the spacing... 

![image](https://user-images.githubusercontent.com/46690235/98701321-c382b600-233e-11eb-819c-ca6cd9767ea0.png)
