### ISSUE TITLE
Generating a pairwise genetic distance matrix for individuals using RADseq data

### ISSUE THREAD

**Issue by redgcko7** [redgcko7/Coleonyx_elegans#5]
I want to run a **Mantel test** in the R program **vegan** to look for **isolation-by-distance** in my gecko samples. The Mantel test requires a **geographic distance matrix** and a **genetic distance matrix**. I generated a geographic distance matrix from coordinates using the program Geographic Distance Matrix Generator (Ersts). I cannot figure out how to generate a genetic distance matrix between samples from my processed RADseq data (vcf file). I have looked into the following programs: hierfstat, adegenet, snprelate, conStruct.

I am confused on the type of genetic distance to use. Fst, p-distances, or something else. All programs that calculate Fst ask for a priori population assignments, which would not be useful to me since I want all samples compared to each other and there are no obvious population breaks, rather samples are broadly collected across the species' range.

I would like to first decide which type of genetic distance to use, then find an appropriate program to calculate this, then format RADseq outfile to be compatible with the input for the program, and generate a genetic distance matrix between samples.

**Comment by NellyJazminPC** [comment]
One package for Mantel Test is https://www.rdocumentation.org/packages/dartR/versions/1.8.3/topics/gl.ibd

**Comment by AliciaMstt** [comment]
If you decide to use FST reember to linearize them using the formula for isolation by distance FST/(1 - FST) as advocated by Rousset (1997)

http://www.genetics.org/cgi/content/abstract/145/4/1219

**Comment by AlexLlanesQuevedo** [comment]
some individual genetic distances that you can use for mantel test can be reviewed at https://dyerlab.github.io/applied_population_genetics/genetic-distances.html

**Comment by AlexLlanesQuevedo** [comment]
another interesting post "Individual Based Genetic Distance for SNP Data" 
https://popgen.nescent.org/2015-05-18-Dist-SNP.html

**Comment by NellyJazminPC** [comment]
Example with `gl.ibd`

```
######### Aislamiento por distancia ################
###lon y lat
library(dartR)
#Extraer los datos de latitud y longitud del metadato
latlong<-data.frame(pop.data$lat, pop.data$long)
latlong  
#Renombrar
names(latlong) <- c("lat", "lon")
#Hacerlo lista
as.list(cgum_79_1_vcf@other$latlong)
# Agregarlo al vcf
cgum_79_1_vcf@other$latlong <- latlong
# Lista
as.list(cgum_79_1_vcf@other$latlong)
#Comprobar
class(cgum_79_1_vcf@other$latlong)
#Correr gl.ibd Mantel Test
ad_cgum_79_1 <-gl.ibd(cgum_79_1_vcf)
```

**Comment by NellyJazminPC** [comment]
Another package to obtain the distance between individuals ishttps://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/dist

_This function computes and returns the distance matrix computed by using the specified distance measure to compute the distances between the rows of a data matrix_ 
Euclidean Method

**Comment by camillethuyentruong** [comment]
Individual-based genetic distance [metrics](https://www.researchgate.net/profile/Mohamed_Mourad_Lafifi/post/What_is_the_best_genetic_distance_metric_to_use_for_highly_polymorphic_microsatellites/attachment/5cf3a396cfe4a7968da65530/AS%3A765290988199937%401559470998395/download/A+comparison+of+individual-based+genetic+distance+metrics+for+landscape+genetics.pdf)

**Comment by NellyJazminPC** [comment]
To convert VCF to genlight format
```
cgum_79_1_genlight <- vcfR2genlight(CGUM_79_1.VCF)
```
To convert format genlight to genind format
```
#install dartR  and use gl2gi convertir de genlight to genind
cgum_79_1_genind <- gl2gi(cgum_79_1_genlight, v=1)
```

**Comment by AlexLlanesQuevedo** [comment]
otra opción es leer directamente de vcf a geneind con vcfR
`
## cargar vcf
my_vcf <- read.vcfR("path/to/vcf")

## convertir el vcf a genind
my_gind <- vcfR2genind(my_vcf)
`

**Comment by redgcko7** [comment]
After talking it over and looking at the links above, we decided that Fst was not the most appropriate form of genetic distance for my dataset, given that you have to define populations for each individual, which is not obvious for the geckos in the dataset. Instead, we decided to try other genetic distance methods, mainly Euclidean distance. We used the program vcfR to import the .vcf file and convert it to a genind object, then we used vegan (or dist function in stats) to calculate euclidean distances between samples. The script used is as follows:
```
library("vcfR")
library("stats")
library("vegan")

# load vcf file
my_vcf <- read.vcfR("Cele95_40.vcf")

# convert vcf to genind object
my_gind <- vcfR2genind(my_vcf)

# OPTION 1: convert genind to euclidean distance matrix using dist function in stats
euc <- dist(my_gind$tab)
euc <- as.matrix(euc)

# OPTION 2: convert euclidean distance with vegan
euc2 <- vegdist(my_gind, method = "euclidean", na.rm = T)
```

Next steps are to remove from the vcf file the 4 individuals that do not have any locality information, re-run the euclidean distance matrix in vegan, import the geographic distance matrix to vegan (already made) and run the Mantel test with vegan.
